# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15.1
ARG NODE_VERSION=22
FROM ghcr.io/daemonless/base:${BASE_VERSION} AS builder
ARG NODE_VERSION

# Install Node.js and build dependencies for native modules (sharp needs libvips;
# sqlite3/lz4/msgpackr-extract compile via node-gyp against the FreeBSD toolchain)
RUN pkg update && \
    pkg install -y \
    FreeBSD-clang \
    FreeBSD-clang-dev \
    FreeBSD-clibs-dev \
    FreeBSD-openssl-dev \
    FreeBSD-zlib-dev \
    FreeBSD-xz-dev \
    FreeBSD-bzip2-dev \
    FreeBSD-toolchain \
    node${NODE_VERSION} \
    npm-node${NODE_VERSION} \
    python312 \
    py312-setuptools \
    vips \
    gmake \
    jq \
    && pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/* && \
    ln -sf /usr/local/bin/python3.12 /usr/local/bin/python3 && \
    ln -sf /usr/local/bin/python3.12 /usr/local/bin/python

# nocodb ships as a prebuilt bundle on npm (dist/bundle.js) — no source build,
# no rspack, no monorepo checkout needed. Resolve+pin the version from the
# same source (npm registry) that upstream-version tracking uses, so the
# installed version, /app/version, and the outdated-check can never skew.
RUN mkdir -p /build && cd /build && \
    NOCODB_VERSION=$(fetch -qo - https://registry.npmjs.org/nocodb/latest | jq -r '.version') && \
    echo "Resolved NOCODB_VERSION=$NOCODB_VERSION" && \
    printf '{"name":"nocodb-wrapper","private":true,"dependencies":{"nocodb":"%s","express":"^4.21.2","cors":"^2.8.5"}}' "$NOCODB_VERSION" > package.json && \
    CXX=/usr/bin/clang++ CC=/usr/bin/clang PYTHON=/usr/local/bin/python3 \
    npm install --omit=dev --dangerously-allow-all-scripts && \
    npm cache clean --force && \
    echo "$NOCODB_VERSION" > /build/version

COPY index.js /build/index.js

# Production image
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG NODE_VERSION
ARG PACKAGES="node${NODE_VERSION} vips"
ARG UPSTREAM_URL="https://registry.npmjs.org/nocodb/latest"
ARG UPSTREAM_JQ=".version"
ARG HEALTHCHECK_ENDPOINT="http://localhost:8080/api/v1/health"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="NocoDB" \
      org.opencontainers.image.description="Free and self-hostable Airtable alternative — turn any database into a smart spreadsheet." \
      org.opencontainers.image.source="https://github.com/daemonless/nocodb" \
      org.opencontainers.image.url="https://nocodb.com/" \
      org.opencontainers.image.documentation="https://docs.nocodb.com/" \
      org.opencontainers.image.licenses="Sustainable-Use-1.0" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Utilities" \
      io.daemonless.port="8080" \
      io.daemonless.volumes="/config" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}"

# Install runtime dependencies (vips is needed at runtime too — sharp links libvips-cpp.so)
RUN pkg update && \
    pkg install -y \
    ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Copy nocodb from builder
COPY --from=builder /build/version /app/version
COPY --from=builder /build/node_modules /app/node_modules
COPY --from=builder /build/index.js /app/index.js
COPY --from=builder /build/package.json /app/package.json

RUN chown -R bsd:bsd /app

# Create config directory
RUN mkdir -p /config && \
    chown -R bsd:bsd /config

# Copy service definitions and init scripts
COPY root/ /

# Make scripts executable
RUN chmod +x /etc/services.d/*/run /etc/cont-init.d/* 2>/dev/null || true

# Environment
ENV NODE_ENV=production \
    PORT=8080

# --- Expose (Injected by Generator) ---
EXPOSE 8080

# --- Volumes (Injected by Generator) ---
VOLUME /config